namespace PositionerDemo
{
    public enum ABILITYMODIFIEREXECUTIONTIME
    {
        EARLY, // SI SE EJECUTA ANTES DE QUE COMIENZE LA HABILIDAD
        LATE // SI SE EJECUTA AL FINAL DE QUE SE EJECUTO LA HABILIDAD
    }

}
