namespace PositionerDemo
{
    public enum ACTIVATIONTYPE
    {
        NONE,
        HAND,
        AUTOMATIC,// SE USA NI BIEN SE LEVANTA, SI NO TIENE TARGET POSIBLE SE DESCARTA
        AUTOMATICNOTDESCARTABLE // SE USA NI BIEN SE LEVANTA, SI NO TIENE TARGET POSIBLES VUELVE A LA MANO
    }
}