using UnityEngine;
namespace PositionerDemo
{
    public class CombineSpawnMotion : Motion
    {
        public CombineSpawnMotion(MonoBehaviour coroutineMono, int reproductionOrder) : base(coroutineMono, reproductionOrder)
        {
            // SPAWN ANIMATION COMBINE

            // ANIMAITION KIMBOKO(N) MOVE
            // TWEEN KIMBOKO(N) A LOS COSTADOS DE LA TILE PARA DAR LUGAR EN EL CENTRO DEL SPAWN

            // INSTANTIATE CRANE//GRUA
            // TWEEN DESDE UNA POSICION ELEVADA SOBRE LA TILE DONDE SE INDICO SPAWNEAR HASTA MAS ABAJO ASI SE VE DESDE ARRIBA EN EL TABLERO SOBRE LA TILE
            // ANIMATION CRANESPAWNING

            // INSTANTIATE KIMBOKO DESDE LA PUNTA DEL CRANE DONDE DEBERIA CHORREAR LA GOTA
            // ANIMATION KIMBOKOSPAWNING
            // TWEEN DESDE LA PUNTA DEL CRANE HASTA EL PISO, DE LA MISMA DURACION QUE LA ANIMACION DE SPAWN
            // ANIMATION IDLLE... TAL VEZ SEA AUTOMATICO EL CAMBIO, PERO POR LAS DUDAS

            // TWEEN DE LA CRANE PARA QUE SALGA DEL MAPA

            // ANIMAITION KIMBOKO(N) + NEW SPAWNED MOVE
            // TWEEN KIMBOKO(N) + NEW SPAWNED A LAS POSICIONES SEGUN LA CANTIDAD QUE ESTEN COMBINADOS
        }
    }

}

