namespace PositionerDemo
{
    public enum OPERATIONTYPE
    {
        SIMPLE, // EL VALOR TAL CUAL ES
        ADITION, // EL VALOR SUMADO OTRO NUMERO
        SUBSTRACTION, // EL VALOR RESTADO OTRO NUMERO
        DIVISION, // EL VALOR DIVIDIDO POR UN NUMERO
        MULTIPLICATION, // EL VALOR MULTIPLICADO POR UN NUMERO
        PERCENT // UN PORCENTAJE DEL VALOR
    }
}
